<?php
/* DO NOT EDIT THIS FILE BAD THINGS MAY HAPPEN */
define("DKPROOT", dirname(__FILE__));
define("DKPMODELS", DKPROOT."/includes/models");

$dkpHooks['dkpawarded'] = array();
$dkpHooks['dkpdeducted'] = array();
$dkpHooks['dkpspent'] = array();
$dkpHooks['bosskill'] = array();
$dkpHooks['newraid'] = array();
$dkpHooks['newattendee'] = array();
?>